services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile # 上記のPoetry対応版Dockerfileを使用
    container_name: ssl_orchestrator
    network_mode: host
    volumes:
      - ./config/config_orchestrator.yaml:/app/config/config_orchestrator.yaml:ro
      - ./config/config_priority.yaml:/app/config/config_priority.yaml:ro
      # (オプション) ログなどをホストに出力したい場合
      # - ./logs/orchestrator:/app/logs
    restart: unless-stopped

  # --- audio_playback など、他のサービスも必要に応じてここに追加 ---
  # ... (省略) ...