# イベント優先度設定ファイル

# 各イベントタイプに対する優先度 (1:低い ～ 10:高い を想定)
# ここに記述する event_type 文字列は、Orchestrator が生成するものと一致させる必要があります
event_priorities:
  # Stage 変更イベント
  STAGE_NORMAL_FIRST_HALF: 1
  STAGE_NORMAL_HALF_TIME: 2
  STAGE_NORMAL_SECOND_HALF: 1
  STAGE_PENALTY_SHOOTOUT: 8 # PK戦は重要度高め
  STAGE_POST_GAME: 1

  # Command 変更イベント
  COMMAND_STOP: 3
  COMMAND_HALT: 9        # HALTは緊急性が高い可能性
  COMMAND_FORCE_START: 2
  COMMAND_KICKOFF_PREP_YELLOW: 4 # 準備系
  COMMAND_KICKOFF_PREP_BLUE: 4
  COMMAND_KICKOFF_START_YELLOW: 6 # 開始系は少し高め
  COMMAND_KICKOFF_START_BLUE: 6
  COMMAND_PENALTY_PREP_YELLOW: 5
  COMMAND_PENALTY_PREP_BLUE: 5
  COMMAND_PENALTY_KICK_START_YELLOW: 7
  COMMAND_PENALTY_KICK_START_BLUE: 7
  COMMAND_DIRECT_FREE_YELLOW: 5
  COMMAND_DIRECT_FREE_BLUE: 5
  COMMAND_TIMEOUT_YELLOW: 7 # タイムアウトは実況の切れ目として重要
  COMMAND_TIMEOUT_BLUE: 7
  COMMAND_BALL_PLACEMENT_YELLOW: 4
  COMMAND_BALL_PLACEMENT_BLUE: 4

  # GameEvent (game_events リスト由来)
  EVENT_BALL_LEFT_TOUCHLINE_YELLOW: 4
  EVENT_BALL_LEFT_TOUCHLINE_BLUE: 4
  EVENT_BALL_LEFT_GOALLINE_YELLOW: 4 # ゴールキック/コーナーキックにつながる
  EVENT_BALL_LEFT_GOALLINE_BLUE: 4
  EVENT_GOAL_CONFIRMED_YELLOW: 10   # ゴールは最重要
  EVENT_GOAL_CONFIRMED_BLUE: 10
  EVENT_PLACEMENT_SUCCEEDED_YELLOW: 3
  EVENT_PLACEMENT_SUCCEEDED_BLUE: 3
  EVENT_PLACEMENT_FAILED_YELLOW: 6 # 失敗は重要度が高いかも？
  EVENT_PLACEMENT_FAILED_BLUE: 6
  EVENT_BOT_PUSHING_YELLOW: 6     # ファウル系
  EVENT_BOT_PUSHING_BLUE: 6
  EVENT_EXCESSIVE_DRIBBLING_YELLOW: 6
  EVENT_EXCESSIVE_DRIBBLING_BLUE: 6
  EVENT_BOT_CRASH_UNIQUE_YELLOW: 7 # クラッシュは少し高め？
  EVENT_BOT_CRASH_UNIQUE_BLUE: 7
  EVENT_BOT_CRASH_DRAWN: 7
  EVENT_UNSPORTING_BEHAVIOR_MINOR_YELLOW: 8 # カード関連は重要
  EVENT_UNSPORTING_BEHAVIOR_MINOR_BLUE: 8

  # ... 他の event_type に対する優先度を定義 ...